(function(f,c){function d(){var b=n.elements;return typeof b=="string"?b.split(" "):b}function e(b){var c={},e=b.createElement,f=b.createDocumentFragment,l=f();b.createElement=function(b){if(!n.shivMethods)return e(b);var d;d=c[b]?c[b].cloneNode():z.test(b)?(c[b]=e(b)).cloneNode():e(b);return d.canHaveChildren&&!A.test(b)?l.appendChild(d):d};b.createDocumentFragment=Function("h,f","return function(){var n=f.cloneNode(),c=n.createElement;h.shivMethods&&("+d().join().replace(/\w+/g,function(b){e(b);
l.createElement(b);return'c("'+b+'")'})+");return n}")(n,l)}function l(b){var c;if(b.documentShived)return b;if(n.shivCSS&&!s){c=b.createElement("p");var d=b.getElementsByTagName("head")[0]||b.documentElement;c.innerHTML="x<style>article,aside,details,figcaption,figure,footer,header,hgroup,nav,section{display:block}audio{display:none}canvas,video{display:inline-block;*display:inline;*zoom:1}[hidden]{display:none}audio[controls]{display:inline-block;*display:inline;*zoom:1}mark{background:#FF0;color:#000}</style>";
c=!!d.insertBefore(c.lastChild,d.firstChild)}w||(c=!e(b));if(c)b.documentShived=c;return b}var t=f.html5||{},A=/^<|^(?:button|form|map|select|textarea|object|iframe|option|optgroup)$/i,z=/^<|^(?:a|b|button|code|div|fieldset|form|h1|h2|h3|h4|h5|h6|i|iframe|img|input|label|li|link|ol|option|p|param|q|script|select|span|strong|style|table|tbody|td|textarea|tfoot|th|thead|tr|ul)$/i,s,w;(function(){var b=c.createElement("a");b.innerHTML="<xyz></xyz>";(s="hidden"in b)&&typeof injectElementWithStyles=="function"&&
injectElementWithStyles("#modernizr{}",function(b){b.hidden=!0;s=(f.getComputedStyle?getComputedStyle(b,null):b.currentStyle).display=="none"});w=b.childNodes.length==1||function(){try{c.createElement("a")}catch(b){return!0}var d=c.createDocumentFragment();return typeof d.cloneNode=="undefined"||typeof d.createDocumentFragment=="undefined"||typeof d.createElement=="undefined"}()})();var n={elements:t.elements||"abbr article aside audio bdi canvas data datalist details figcaption figure footer header hgroup mark meter nav output progress section summary time video",
shivCSS:t.shivCSS!==!1,shivMethods:t.shivMethods!==!1,type:"default",shivDocument:l};f.html5=n;l(c)})(this,document);(function(f){f.Placeholders={Utils:{addEventListener:function(c,d,e){if(c.addEventListener)return c.addEventListener(d,e,!1);if(c.attachEvent)return c.attachEvent("on"+d,e)},inArray:function(c,d){var e,f;e=0;for(f=c.length;e<f;e++)if(c[e]===d)return!0;return!1},moveCaret:function(c,d){var e;c.createTextRange?(e=c.createTextRange(),e.move("character",d),e.select()):c.selectionStart&&(c.focus(),c.setSelectionRange(d,d))},changeType:function(c,d){try{return c.type=d,!0}catch(e){return!1}}}}})(this);
(function(f){function c(a){var b;if(a.value===a.getAttribute(j)&&a.getAttribute(m)==="true"){a.setAttribute(m,"false");a.value="";a.className=a.className.replace(E,"");if(b=a.getAttribute(o))a.type=b;return!0}return!1}function d(a){var b;if(a.value==="")return a.setAttribute(m,"true"),a.value=a.getAttribute(j),a.className+=" "+y,(b=a.getAttribute(o))?a.type="text":a.type==="password"&&h.changeType(a,"text")&&a.setAttribute(o,"password"),!0;return!1}function e(a,b){var c,d,e,g,f;if(a&&a.getAttribute(j))b(a);
else{c=a?a.getElementsByTagName("input"):c;d=a?a.getElementsByTagName("textarea"):d;f=0;for(g=c.length+d.length;f<g;f++)e=f<c.length?c[f]:d[f-c.length],b(e)}}function l(a){e(a,c)}function t(a){return function(){B&&a.value===a.getAttribute(j)&&a.getAttribute(m)==="true"?h.moveCaret(a,0):c(a)}}function A(a){return function(){d(a)}}function z(a){return function(b){C=a.value;if(a.getAttribute(m)==="true")return!(C===a.getAttribute(j)&&h.inArray(K,b.keyCode))}}function s(a){return function(){var b;if(a.getAttribute(m)===
"true"&&a.value!==C&&(a.className=a.className.replace(E,""),a.value=a.value.replace(a.getAttribute(j),""),a.setAttribute(m,!1),b=a.getAttribute(o)))a.type=b;a.value===""&&(a.blur(),h.moveCaret(a,0))}}function w(a){return function(){a===document.activeElement&&a.value===a.getAttribute(j)&&a.getAttribute(m)==="true"&&h.moveCaret(a,0)}}function n(a){return function(){l(a)}}function b(a){if(a.form)u=a.form,u.getAttribute(F)||(h.addEventListener(u,"submit",n(u)),u.setAttribute(F,"true"));h.addEventListener(a,
"focus",t(a));h.addEventListener(a,"blur",A(a));B&&(h.addEventListener(a,"keydown",z(a)),h.addEventListener(a,"keyup",s(a)),h.addEventListener(a,"click",w(a)));a.setAttribute(G,"true");a.setAttribute(j,q);d(a)}var D=["text","search","url","tel","email","password","number","textarea"],K=[27,33,34,35,36,37,38,39,40,8,46],y="placeholdersjs",E=RegExp("\\b"+y+"\\b"),k,r,j="data-placeholder-value",m="data-placeholder-active",o="data-placeholder-type",F="data-placeholder-submit",G="data-placeholder-bound",
p=document.createElement("input"),H=document.getElementsByTagName("head")[0],v=document.documentElement,f=f.Placeholders,h=f.Utils,B,I,C,q,J,u,g,x,i;if(p.placeholder===void 0){k=document.getElementsByTagName("input");r=document.getElementsByTagName("textarea");B=v.getAttribute("data-placeholder-focus")==="false";I=v.getAttribute("data-placeholder-live")!=="false";p=document.createElement("style");p.type="text/css";v=document.createTextNode("."+y+" { color:#ccc; }");p.styleSheet?p.styleSheet.cssText=
v.nodeValue:p.appendChild(v);H.insertBefore(p,H.firstChild);i=0;for(x=k.length+r.length;i<x;i++)g=i<k.length?k[i]:r[i-k.length],(q=g.getAttribute("placeholder"))&&h.inArray(D,g.type)&&b(g);J=setInterval(function(){i=0;for(x=k.length+r.length;i<x;i++)if(g=i<k.length?k[i]:r[i-k.length],(q=g.getAttribute("placeholder"))&&h.inArray(D,g.type))if(g.getAttribute(G)||b(g),q!==g.getAttribute(j)||g.type==="password"&&!g.getAttribute(o)){g.type==="password"&&!g.getAttribute(o)&&h.changeType(g,"text")&&g.setAttribute(o,
"password");if(g.value===g.getAttribute(j))g.value=q;g.setAttribute(j,q)}I||clearInterval(J)},100)}f.disable=l;f.enable=function(a){e(a,d)}})(this);